---

- name: Update apt-cache
  apt:
    update_cache: yes

- name: Install build tools and dependencies
  apt:
    name: ['gcc', 'g++', 'make', 'cmake', 'build-essential', 'git', 'libxtables-dev',
        'libip6tc-dev', 'libip4tc-dev', 'libiptc-dev', 'libavfilter-dev', 'libavcodec-dev', 'libswresample-dev',
        'libevent-dev', 'libpcap-dev', 'libxmlrpc-core-c3-dev', 'markdown', 'libjson-glib-dev',
        'libhiredis-dev', 'libssl-dev', 'libcurl4-openssl-dev', 'gperf', 'libspandsp-dev', 'libwebsockets-dev', 'libopus-dev',
        'libmnl-dev', 'libnftnl-dev', 'pandoc', 'libncurses-dev', 'linux-headers-amd64', 'linux-source', 'linux-source-6.1']
    state: present

- name: Install mysql client
  apt:
    name: ['libmysqlclient-dev']
    state: present
  when: ansible_distribution != 'Debian'

- name: Install mysql client
  apt:
    name: ['default-libmysqlclient-dev']
    state: present
  when: ansible_distribution == 'Debian'

- name: make source directory writeable
  file:
    path: /usr/local/src
    state: directory
    mode: '0777'

- name: checkout bcg729 encoder/decoder
  git:
    repo: https://github.com/BelledonneCommunications/bcg729.git
    dest: /usr/local/src/bcg729
    version: master
    depth: 50
    accept_hostkey: yes
    force: yes
  become: false

- name: ensure bcg729 was cloned successful
  stat:
    path: "/usr/local/src/bcg729"
  register: bcg729_exist 

- name: build bcg729
  shell: |
    cmake . -DCMAKE_INSTALL_PREFIX=/usr

    make

    make install chdir=/usr/local/src/bcg729
    
    exit 0
  args:
    chdir: /usr/local/src/bcg729
  become: true
  when: bcg729_exist|bool

- name: check out rtpengine
  git:
    repo: https://github.com/sipwise/rtpengine.git
    dest: /usr/local/src/rtpengine
    version: '{{ rtp_engine_version }}'
    depth: 50
    accept_hostkey: true
    force: true
  become: false

- name: check exist rtpengine source
  stat:
    path: /usr/local/src/rtpengine
  register: rtpengine_source_exist

- name: build rtpengine
  command:
    chdir: /usr/local/src/rtpengine
    argv:
    - make
    - with_transcoding=yes
    - '{{ enable_kernel }}'
    - chdir=/usr/local/src/rtpengine/daemon
  register: build_rtpengine_result
  # when: rtpengine_source_exist.stat.exists

- name: install rtpengine {{ build_rtpengine_result }}
  command: cp /usr/local/src/rtpengine/daemon/rtpengine /usr/local/bin
  # when: build_rtpengine_result.failed != false

- name: Create systemd unit file
  template:
    src: rtpengine.service.j2
    dest: /etc/systemd/system/rtpengine.service
    mode: '0644'
    owner: root
    group: root

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services

- name: systemctl daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: (re)start rtpengine
  service:
    name: rtpengine
    enabled: true
    state: restarted

- name: remove source code
  file:
    path: /usr/local/src/rtpengine
    state: absent
  when: remove_source|bool
